apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-vs
  namespace: zpf
spec:
  hosts:
    - "my.test.com"
  gateways:
    - test-gateway
  http:
    - match:
        - uri:
            prefix: /consumer
      route:
        - destination:
            host: test-consumer
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-provider
  namespace: zpf
spec:
  hosts:
    - test-provider
  http:
    - route:
        - destination:
            host: test-provider
            subset: v1
          weight: 20
        - destination:
            host: test-provider
            subset: v2
          weight: 80
