apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-test
  namespace: zpf

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-test
  namespace: zpf
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-test
  namespace: zpf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-test
subjects:
  - kind: ServiceAccount
    name: cloud-test
    namespace: zpf
