server:
  port: 7070
  servlet:
    context-path: /consumer
spring:
  application:
    name: test-consumer
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connect-timeout: 9000
        read-timeout: 9000
        log-level: full
        retryer: feign.Retryer.Default
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false
        isolation:
          thread:
            timeoutInMilliseconds: 15000
