apiVersion: v1
kind: Service
metadata:
  name: test-consumer
  namespace: zpf
  labels:
    app: test-consumer
spec:
  selector:
    app: test-consumer
  ports:
    - port: 7070
      targetPort: 7070
      name: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-consumer
  namespace: zpf
  labels:
    app: test-consumer
    version: v1
spec:
  selector:
    matchLabels:
      app: test-consumer
      version: v1
  template:
    metadata:
      namespace: zpf
      labels:
        app: test-consumer
        version: v1
    spec:
      serviceAccountName: cloud-test
      containers:
        - name: test-consumer
          image: tubetrue01/test-consumer:v1
          ports:
            - containerPort: 7070
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: log-path
              mountPath: /var/log/springcloud/test-consumer
      volumes:
        - name: log-path
          hostPath:
            path: /var/log/springcloud/test-consumer


